import click
import yaml
from os.path import join
from subprocess import call


# setup command line arguments and options
@click.command()
@click.argument('notebook')
@click.option('--nbloc', default='notebooks')
@click.option('--imglist', default='util/nbprocess.yml')
@click.option('--siteloc', default='docs')
def cli(notebook, nbloc, imglist, siteloc):
    # convert notebook to markdown
    call(['jupyter', 'nbconvert', join(nbloc, notebook + '.ipynb'), '--to',  'markdown'])

    # read list of image names
    f = open(imglist, 'r')
    images = yaml.safe_load(f)[notebook]
    f.close()

    # open files
    fsource = open(join(nbloc, notebook + '.md'), 'r')
    ftarget = open(join(siteloc, '_pages', notebook + '.md'), 'w')
    index = 0

    # read source file line by line
    for line in fsource:
        if '![png]' in line:
            # replace image path generated by nbconvert
            imgloc = join('{{ site.baseurl }}', 'assets', 'images', notebook, images[index])
            line = '![png]({}.png){}'.format(imgloc, '{: .center-image }')
            index += 1

        # write line to target file
        ftarget.write(line)

    # close files
    fsource.close()
    ftarget.close()
